### ISSUE TITLE
Power Stars cannot share the same ID. If multiple share, the game will crash on loading a save, or collecting a star.

### ISSUE THREAD

**Issue by gayfrogog** [SuperHackio/Scenaristar#3]
Found through the first Luma's Workshop competition.

Possible solution: Multiply the star number by the galaxy's hash and modulus it by the total amount of possible power stars.
Or just check if multiple galaxies have the same value for their Power Star IDs.

**THIS DOES NOT APPLY TO GREEN STARS**

**Comment by gayfrogog** [comment]
Should note that it doesn't apply to *all* stars. However it does apply to PS ID 2 at the very least.

**Comment by SuperHackio** [comment]
This sounds very suspicious. Will look into either limiting this or fixing the underlying issue (if applicable)

**Comment by SuperHackio** [comment]
Could you show some screenshots of the problematic scenario as loaded in Scenaristar?
I would also appreciate if you used the word terms used by Scenaristar, as I cannot pinpoint which value you're reffering to when you say "Power Star IDs", or "PS ID".

**Comment by gayfrogog** [comment]
For one, there's a scenario number and a Power Star ID. I'm purely going off of the BCSV editor, since that's something that *everyone* knows the values for. Here's the first version of the competition release that crashed spectacularly due to this issue.
[Competition1.zip](https://github.com/SuperHackio/Scenaristar/files/6564158/Competition1.zip)

**Comment by SuperHackio** [comment]
I have analyzed these files, and I have found the two problematic scenario files:

# MarioOnMarioGalaxy
![image](https://user-images.githubusercontent.com/44330283/120120399-c9f94380-c151-11eb-8219-5ee5fcecb98b.png)

The green star has Star 1 checked off as being available. This is a mistake by the creator of the scenario file, and is most likely what you are referring to, as having the same settings on both stars sets one of the BCSV values as being equal. (in the GUI, this field is labelled as "Star Code", which is a composition of the star checkboxes)


# SecretAthleticGalaxy
![image](https://user-images.githubusercontent.com/44330283/120120428-fd3bd280-c151-11eb-9fb6-c3085dbc4667.png)

The first star marks both Star 3 and 4 as being available, despite the fact there's only 2 stars

![image](https://user-images.githubusercontent.com/44330283/120120452-33795200-c152-11eb-8d4b-a40a9d0471df.png)

The green star is marked to be Scenario 3 when it should be Scenario 2
The Star 3 checkbox is checked, when the Star 2 checkbox should be checked. (If this green star was actually the third scenario, Star 3 being checked would be correct)


## Conclusion
These are not issues of Scenaristar itself, rather mistakes done by users of Scenaristar, or users of the BCSV editor that everyone supposedly knows. Thus, I am not obligated to fix anything.

It would appear that most people understand how to setup scenarios properly, but perhaps clarification on how to setup green stars would be needed.

**Comment by gayfrogog** [comment]
No, you got it wrong. That's not the issue. The game crashes upon collecting any star. I may have explained the wrong crash. The 'Star Code' is the issue. Since changing that to a random number for every single galaxy fixed the collection crash.

The game crashes during Lubba's text initialisation code according to shibbo.

**Every** level worked perfectly on its own, however they crashed upon being brought together due to clashing scenarios.
Also, green stars work fine setup like that.
